<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MD2112N" ignored="0" name="Default test" tests="4" failures="1" timestamp="27 Jun 2020 05:48:12 GMT" time="2.108" errors="0">
  <testcase name="CreateCustomerAPIInvalid" time="1.566" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.automation.APIautomationFramework.testcases.CreateCustomerTest.CreateCustomerAPIInvalid(CreateCustomerTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CreateCustomerAPIInvalid -->
  <testcase name="CreateCustomerAPIValid" time="0.002" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
    <skipped/>
  </testcase> <!-- CreateCustomerAPIValid -->
  <testcase name="CreateCustomerAPIValid" time="0.465" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest"/>
  <testcase name="CreateCustomerAPIValid" time="0.465" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest"/>
</testsuite> <!-- Default test -->
