<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MD2112N" ignored="0" name="CreateCustomerTest" tests="4" failures="1" timestamp="22 Jul 2020 01:20:04 GMT" time="2.221" errors="0">
  <testcase name="CreateCustomerAPIInvalid" time="1.647" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.automation.APIautomationFramework.testcases.CreateCustomerTest.CreateCustomerAPIInvalid(CreateCustomerTest.java:95)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- CreateCustomerAPIInvalid -->
  <testcase name="CreateCustomerAPIValid" time="0.005" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
    <skipped/>
  </testcase> <!-- CreateCustomerAPIValid -->
  <testcase name="CreateCustomerAPIValid" time="0.482" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest"/>
  <testcase name="CreateCustomerAPIValid" time="0.535" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest"/>
</testsuite> <!-- CreateCustomerTest -->
