<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MD2112N" ignored="0" name="DeleteCustomerTest" tests="1" failures="1" timestamp="23 Jul 2020 02:48:24 GMT" time="1.791" errors="0">
  <testcase name="DeleteCustomer" time="1.761" classname="com.automation.APIautomationFramework.testcases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.automation.APIautomationFramework.testcases.DeleteCustomerTest.DeleteCustomer(DeleteCustomerTest.java:50)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- DeleteCustomer -->
</testsuite> <!-- DeleteCustomerTest -->
