<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" ignored="0" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2143" started-at="2020-07-23T02:48:22Z" finished-at="2020-07-23T02:48:24Z">
    <groups>
    </groups>
    <test name="DeleteCustomerTest" duration-ms="1791" started-at="2020-07-23T02:48:22Z" finished-at="2020-07-23T02:48:24Z">
      <class name="com.automation.APIautomationFramework.testcases.DeleteCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.automation.APIautomationFramework.testcases.DeleteCustomerTest@2f54a33d]" name="setUp" is-config="true" duration-ms="416" started-at="2020-07-23T12:48:21Z" finished-at="2020-07-23T12:48:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="DeleteCustomer(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.DeleteCustomerTest@2f54a33d]" name="DeleteCustomer" duration-ms="1761" started-at="2020-07-23T12:48:22Z" data-provider="data" finished-at="2020-07-23T12:48:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, id=cus_HguK9iKn87CvrJ}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.automation.APIautomationFramework.testcases.DeleteCustomerTest.DeleteCustomer(DeleteCustomerTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.automation.APIautomationFramework.testcases.DeleteCustomerTest@2f54a33d]" name="tearDown" is-config="true" duration-ms="0" started-at="2020-07-23T12:48:24Z" finished-at="2020-07-23T12:48:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.automation.APIautomationFramework.testcases.DeleteCustomerTest -->
    </test> <!-- DeleteCustomerTest -->
    <test name="CreateCustomerTest" duration-ms="2143" started-at="2020-07-23T02:48:22Z" finished-at="2020-07-23T02:48:24Z">
      <class name="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
        <test-method status="FAIL" signature="CreateCustomerAPIInvalid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.CreateCustomerTest@5609159b]" name="CreateCustomerAPIInvalid" duration-ms="1513" started-at="2020-07-23T12:48:22Z" data-provider="data" finished-at="2020-07-23T12:48:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=java@way2automation.com, name=Rahul Arora, Runmode=row 9 or column 0 does not exist  in xls, description=Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.automation.APIautomationFramework.testcases.CreateCustomerTest.CreateCustomerAPIInvalid(CreateCustomerTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIInvalid -->
        <test-method status="SKIP" signature="CreateCustomerAPIValid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.CreateCustomerTest@5609159b]" name="CreateCustomerAPIValid" duration-ms="1" started-at="2020-07-23T12:48:23Z" data-provider="data" finished-at="2020-07-23T12:48:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=ishita@way2automation.com, name=Ishita Arora, Runmode=Y, description=Adding the forth Customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test skipped since rumode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test skipped since rumode is N
	at com.automation.APIautomationFramework.testcases.CreateCustomerTest.CreateCustomerAPIValid(CreateCustomerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIValid -->
        <test-method status="PASS" signature="CreateCustomerAPIValid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.CreateCustomerTest@5609159b]" name="CreateCustomerAPIValid" duration-ms="589" started-at="2020-07-23T12:48:23Z" data-provider="data" finished-at="2020-07-23T12:48:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=corporate@way2automation.com, name=Raman Arora, Runmode=Y, description=Adding the Third Customer in Framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIValid -->
        <test-method status="SKIP" signature="CreateCustomerAPIValid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.CreateCustomerTest@5609159b]" name="CreateCustomerAPIValid" duration-ms="1" started-at="2020-07-23T12:48:23Z" data-provider="data" finished-at="2020-07-23T12:48:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=java@way2automation.com, name=Rahul Arora, Runmode=N, description=Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test skipped since rumode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test skipped since rumode is N
	at com.automation.APIautomationFramework.testcases.CreateCustomerTest.CreateCustomerAPIValid(CreateCustomerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIValid -->
      </class> <!-- com.automation.APIautomationFramework.testcases.CreateCustomerTest -->
    </test> <!-- CreateCustomerTest -->
  </suite> <!-- Suite -->
</testng-results>
